@startuml hinh3.2-vong-lap-traci

skinparam defaultFontSize 13
skinparam defaultFontName Arial
skinparam ArrowColor #555555
skinparam ArrowThickness 1.5

skinparam activity {
    BackgroundColor #dae8fc
    BorderColor     #6c8ebf
    BorderThickness 1.5
    FontColor       #1a1a1a
}
skinparam activityDiamondBackgroundColor #fff2cc
skinparam activityDiamondBorderColor     #d6b656

start

:Kết nối SUMO;

repeat
  :Thực thi bước thời gian;
  :Lấy trạng thái;
  :Gửi sang Unity;
repeat while (còn bước mô phỏng?) is (có)
->không;

stop

@enduml
