@startuml hinh2.6-usecase-nhom-D
left to right direction
skinparam packageStyle rectangle
skinparam usecaseBorderColor #333333
skinparam usecaseBackgroundColor #FEFECE
skinparam actorBorderColor #333333
skinparam ArrowColor #333333

actor "Người dùng" as User
actor "SUMO" as SUMO

rectangle "Lái xe tương tác" {
  usecase "Chiếm quyền\nvà lái xe" as UC14
  usecase "Trả quyền\nđiều khiển" as UC15
  usecase "Xử lý va chạm\nsinh xác xe" as UC16
}

User -- UC14
User -- UC15
UC14 -- SUMO
UC15 -- SUMO

UC16 .> UC14 : <<extend>>

@enduml
