@startuml hinh2.4-usecase-nhom-B
left to right direction
skinparam packageStyle rectangle
skinparam usecaseBorderColor #333333
skinparam usecaseBackgroundColor #FEFECE
skinparam actorBorderColor #333333
skinparam ArrowColor #333333

actor "Người dùng" as User
actor "SUMO" as SUMO

rectangle "B. Vận hành mô phỏng" {
  usecase "UC6. Chạy thời\ngian thực" as UC6
  usecase "UC7. Chạy chế độ\nphát lại" as UC7
  usecase "UC8. Chạy kèm\nsumo-gui" as UC8
  usecase "Hiển thị phương tiện" as INC1
  usecase "Hiển thị đèn tín hiệu" as INC2
  usecase "Hiển thị người đi bộ" as INC3
}

User -- UC6
User -- UC7
User -- UC8
UC6 -- SUMO
UC7 -- SUMO
UC8 -- SUMO

UC6 .> INC1 : <<include>>
UC6 .> INC2 : <<include>>
UC7 .> INC3 : <<include>>

@enduml
