@startuml hinh4.1-kien-truc-chi-tiet-tcp
left to right direction

skinparam defaultFontSize 13
skinparam defaultFontName Arial
skinparam ArrowColor #555555
skinparam ArrowThickness 1.5

skinparam component {
    BackgroundColor #dae8fc
    BorderColor     #6c8ebf
    BorderThickness 1.5
    FontColor       #1a1a1a
}

component "SUMO\n(mô phỏng vi mô)" as SUMO
component "Python\n(điều phối)" as PY
component "Unity\n(hiển thị & tương tác)" as UNITY

SUMO <--> PY : TraCI

PY    -->  UNITY : 5050: dữ liệu mô phỏng
UNITY -->  PY    : 5053: vị trí xe người lái
UNITY -->  PY    : 5054: lệnh điều khiển

@enduml
