@startuml hinh2.3-usecase-nhom-A
left to right direction
skinparam packageStyle rectangle
skinparam usecaseBorderColor #333333
skinparam usecaseBackgroundColor #FEFECE
skinparam actorBorderColor #333333
skinparam ArrowColor #333333

actor "Người dùng" as User

rectangle "Chuẩn bị kịch bản & bản đồ" {
  usecase "Tạo bản đồ\ntừ mê cung" as UC1
  usecase "Nhập bản đồ\nOpenStreetMap" as UC2
  usecase "Nạp kịch bản\ntự dựng (netedit)" as UC3
  usecase "Sinh tuyến\ncho phương tiện" as UC4
  usecase "Sinh tuyến\ncho người đi bộ" as UC5
  usecase "Cấu hình\ntham số mô phỏng" as UC6
}

User -- UC1
User -- UC2
User -- UC3
User -- UC4
User -- UC5
User -- UC6

@enduml
