@startuml hinh2.7-usecase-nhom-E
left to right direction
skinparam packageStyle rectangle
skinparam usecaseBorderColor #333333
skinparam usecaseBackgroundColor #FEFECE
skinparam actorBorderColor #333333
skinparam ArrowColor #333333

actor "Người dùng" as User

rectangle "Kết quả & lưu trữ" {
  usecase "Ghi và lưu trữ\nphiên mô phỏng" as UC17
}

User -- UC17

@enduml
