@startuml hinh2.5-usecase-nhom-C
left to right direction
skinparam packageStyle rectangle
skinparam usecaseBorderColor #333333
skinparam usecaseBackgroundColor #FEFECE
skinparam actorBorderColor #333333
skinparam ArrowColor #333333

actor "Người dùng" as User

rectangle "Quan sát & điều khiển" {
  usecase "Điều khiển\ncamera quan sát" as UC10
  usecase "Tạm dừng /\ntiếp tục" as UC11
  usecase "Điều chỉnh\ntốc độ" as UC12
  usecase "Lọc đối tượng\nhiển thị" as UC13
}

User -- UC10
User -- UC11
User -- UC12

UC13 .> UC10 : <<extend>>

@enduml
