@startuml hinh2.9-hoat-dong-uc14
skinparam defaultFontName Arial
skinparam defaultFontSize 13
skinparam ActivityBackgroundColor #FEFECE
skinparam ActivityBorderColor #333333
skinparam ArrowColor #333333
skinparam ActivityDiamondBackgroundColor #FEFECE
skinparam ActivityDiamondBorderColor #333333

start

:Người dùng yêu cầu trả quyền;

if (Xe bị va chạm?) then (Có)
  :Chuyển xử lý xác xe (UC15);
else (Không)
  :Tìm làn đường gần nhất;
  if (Trong ngưỡng khoảng cách?) then (Có)
    :Đưa về làn, cấp tuyến,\ntrả quyền cho SUMO;
  else (Không)
    :Loại bỏ phương tiện;
  endif
endif

stop

@enduml
